version: "@head"
export: |
    project "bimg"
        kind "StaticLib" 

        files {
            "3rdparty/**.h",
            "3rdparty/**.hpp",
            "3rdparty/**.cpp",
            "include/**.h",
            "src/**.cpp",
            "src/**.h"
        }

        includedirs {
            "3rdparty",
            "3rdparty/nvtt",
            "3rdparty/iqa/include"
        }

        zpm.uses "Zefiros-Software/bx"

        filter "system:linux"
            pic "on"

        zpm.export(function()

            includedirs "include"

        end)