version: "@head"
export: |
    project "bimg"
        kind "StaticLib" 

        files {
            "3rdparty/**.h",
            "3rdparty/**.hpp",
            "3rdparty/**.cpp",
            "include/**.h",
            "src/image.*",
            "src/image_decode.*",
            "src/image_gnf.cpp",
            "src/image_encode.*",
            "3rdparty/libsquish/**.cpp",
            "3rdparty/libsquish/**.h",
            "3rdparty/edtaa3/**.cpp",
            "3rdparty/edtaa3/**.h",
            "3rdparty/etc1/**.cpp",
            "3rdparty/etc1/**.h",
            "3rdparty/etc2/**.cpp",
            "3rdparty/etc2/**.hpp",
            "3rdparty/nvtt/**.cpp",
            "3rdparty/nvtt/**.h",
            "3rdparty/pvrtc/**.cpp",
            "3rdparty/pvrtc/**.h",
            "3rdparty/tinyexr/**.h",
            "3rdparty/iqa/include/**.h",
            "3rdparty/iqa/source/**.c"
        }

        includedirs {
            "3rdparty",
            "3rdparty/nvtt",
            "3rdparty/iqa/include"
        }

        zpm.uses "Zefiros-Software/bx"

        filter "system:linux"
            pic "on"

        zpm.export(function()

            includedirs "include"

        end)